"""add sub_images to photos

Revision ID: 618c49b1645c
Revises: fd56ab9a5f2c
Create Date: 2026-06-23 22:33:43.031312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618c49b1645c'
down_revision = 'fd56ab9a5f2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('sub_images', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'sub_images')
    # ### end Alembic commands ###
